services:
  db:
    image: mysql:8.0
    container_name: tienda_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tienda_playeras
      MYSQL_USER: tienda_user
      MYSQL_PASSWORD: tienda_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-db:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

    networks:
      - veon-network

  mongodb:
    image: mongo:latest
    container_name: tienda_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - veon-network

  payara-container:
    build:
      context: ./ServidorTiendaPlayeras
      dockerfile: Dockerfile

    container_name: payara-container
    restart: unless-stopped

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: tienda_playeras
      DB_USER: tienda_user
      DB_PASSWORD: tienda_password
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: tienda_playeras

    ports:
      - "8080:8080"
      - "4848:4848"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - veon-network

  frontend:
    build:
      context: ./ClienteTiendaPlayeras
      dockerfile: Dockerfile

    container_name: tienda_frontend
    restart: unless-stopped

    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      PRODUCTOS_API_URL: http://payara-container:8080/ServidorTiendaPlayeras/ProductoServlet
      USUARIOS_API_URL: http://payara-container:8080/ServidorTiendaPlayeras/api/auth
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync

    ports:
      - "8000:80"

    depends_on:
      payara-container:
        condition: service_started

    networks:
      - veon-network

networks:
  veon-network:
    name: veon-network
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
